<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            position: relative;
        }

        /* Watermark */
        body::before {
            content: "{{ Auth::guard('EXT')->user()->upn_no }}KSG";
            position: absolute;
            font-size: 60px;
            color: rgba(0, 0, 0, 0.1);
            top: 35%;
            left: 10%;
            transform: rotate(-30deg);
            z-index: -1;
            font-weight: bold;
        }

        .container {
            width: 100%;
            padding: 20px;
        }

        /* Logo Styling */
        .images-container {
            text-align: center;
            margin-bottom: 10px;
        }

        .logo-icon {
            margin: 0 10px;
            vertical-align: middle;
        }

        .header {
            text-align: center;
            background-color: #007bff;
            color: white;
            padding: 15px;
            font-size: 24px;
            font-weight: bold;
        }

        .sub-header {
            text-align: center;
            font-size: 18px;
            font-weight: bold;
            margin-top: 5px;
        }
        table thead th {
        background-color: rgb(203, 211, 0); /* Header background */
        color: rgb(127, 98, 44); /* Header text */
        padding: 10px;
        text-align: left;
    }

    table {
    border-collapse: collapse;
    width: 100%;
}

th {
    background-color: rgb(203, 211, 0); /* Background color */
    color: rgb(127, 98, 44); /* Text color */
    border: 1px solid black;
    padding: 10px;
    text-align: left;
}

td {
    border: 1px solid black;
    padding: 10px;
    text-align: left;
}

        th {
            background-color: #007bff;
            color: white;
        }

        .section-title {
            background-color: #f0f0f0;
            padding: 10px;
            font-size: 18px;
            font-weight: bold;
            margin-top: 20px;
        }

        /* Footer */
        .footer {
            position: fixed;
            bottom: 0;
            left: 0;
            width: 100%;
            text-align: center;
            font-size: 12px;
            padding: 10px;
            background-color: #007bff;
            color: white;
        }
    </style>
</head>
<body>

    <!-- Logo Section -->
    <div class="images-container">
        <img src="{{ public_path('assets/images/output-onlinepngtools (3).png') }}" class="logo-icon" alt="logo icon" height="66px" width="70px">
        <img src="{{ public_path('assets/images/COA_Line__1.png') }}" class="logo-icon" alt="logo icon" height="66px" width="5px">
        <img src="{{ public_path('assets/images/KSG Logo (1).png') }}" class="logo-icon" alt="logo icon" height="66px" width="90px">
    </div>

    <!-- Header -->
    <div class="header text-center" style="background-color: rgb(203, 211, 0); color: rgb(127, 98, 44); padding: 10px; font-size: 20px; font-weight: bold; border-radius: 5px;">
        Complete User Report
    </div>
    
    <style>
        .sub-header {
            color: rgb(203, 211, 0); /* Text color */
            font-weight: bold; /* Bold text */
        }
    </style>
    
    <div class="sub-header">Generated by {{ Auth::guard('EXT')->user()->name }}</div>
    

    <div class="container">
        <!-- User Details -->
        <div class="section-title">User Details</div>
       <table id="coreMandateTable" class="table mb-0">
    <thead class="table-light">
         <tr>
        <th>Full Name</th>
        <td>{{ Auth::guard('EXT')->user()->name }}</td>
        <th>E-Mail</th>
        <td>{{ Auth::guard('EXT')->user()->email }}</td>
    </tr>
    <tr>
        <th>Phone Number</th>
        <td>{{ Auth::guard('EXT')->user()->mobile_no }}</td>
        <th>Date of Birth</th>
        <td>{{ Auth::guard('EXT')->user()->dob }}</td>
    </tr>
    <tr>
        <th>Nationality</th>
        <td>{{ Auth::guard('EXT')->user()->nationality }}</td>
        <th>Postal Address</th>
        <td>{{ Auth::guard('EXT')->user()->postal_address }}</td>
    </tr>
    <tr>
        <th>Gender</th>
        <td>{{ Auth::guard('EXT')->user()->gender }}</td>
        <th>Ethnicity</th>
        <td>{{ Auth::guard('EXT')->user()->ethnicity }}</td>
    </tr>
    <tr>
        <th>ID Number</th>
        <td>{{ Auth::guard('EXT')->user()->idnumber }}</td>
        <th>Home County</th>
        <td>{{ Auth::guard('EXT')->user()->home_county }}</td>
    </tr>
    <tr>
        <th>Disability</th>
        <td>{{ Auth::guard('EXT')->user()->disability }}</td>
        <th>Description</th>
        <td>{{ Auth::guard('EXT')->user()->disability_description }}</td>
    </tr>
    </thead>
</table>


        <!-- Academic Qualifications -->
        <div class="section-title">Academic Qualifications</div>
        <table id="example" class="table mb-0">
            <thead class="table-light">
            <tr>
                <th>#</th>
                            <th>Education Type</th>
                            <th>Institution</th>
                            <th>Course</th>
                            <th>Level</th>
                            <th>Start Date</th>
                            <th>End Date</th>
                            <th>Grade</th>
                          
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($academics as $index => $academic)
                        <tr>
                            <td>{{ $index + 1 }}</td>
                            <td>{{ $academic->Education_type }}</td>
                            <td>{{ $academic->institution }}</td>
                            <td>{{ $academic->course }}</td>
                            <td>{{ $academic->level }}</td>
                            <td>{{ date('d M Y', strtotime($academic->stdate)) }}</td>
                            <td>{{ date('d M Y', strtotime($academic->enddate)) }}</td>
                            <td>{{ $academic->grade }}</td>
            </tr>
            @endforeach
        </table>

        <!-- Work Experience -->
        <div class="section-title">Work Experience</div>
        <table id="coreMandateTable" class="table mb-0">
            <thead class="table-light">
            <tr>
                <th>Employer</th>
                            <th>Job Title</th>
                            <th>Country</th>
                            <th>Start Date</th>
                            <th>End Date</th>
                            <th>Location</th>
                            <th>Job Description</th>
                            <th>Duties  and  Responsibilities</th>
                            
                      

                        </tr>
                    </thead>
                    <tbody>
                        @forelse($experiences as $experience)
                        <tr>
                            <td>{{ $experience->employer }}</td>
                            <td>{{ $experience->job_title }}</td>
                            <td>{{ $experience->country }}</td>
                            <td>{{ date('d M Y', strtotime($experience->stdate)) }}</td>
                            <td>{{ date('d M Y', strtotime($experience->enddate)) }}</td>
                            <td>{{ $experience->location }}</td>
                            <td>{{ $experience->expartise }}</td>
                            <td>{{ $experience->duties }}</td>
                        
            </tr>
            @endforeach
        </table>
    </div>
     
    <div class="container mt-5">
        <!-- Core Mandate Section -->
       

        <!-- Licenses Section -->
        

        <!-- Professional Body Section -->
        <div class="mb-5">
            <h2>Professional Body</h2>
            
            <table id="professionalBodyTable" class="table mb-0">
                <thead class="table-light">
                    <tr>
                        <th>ID</th>
                        <th>I am a member</th>
                        <th>Professional Body Name</th>
                        <th>Regulating Law/Statute</th>
                        <th>Status</th>
                        <th>Certificate</th>
                        <th>Certificate  Name</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($profecionalbodies as $data)
                        <tr>
                            <td>{{ $data->id }}</td>
                            <td>{{ $data->is_member }}</td>
                            <td>{{ $data->professional_body }}</td>
                            <td>{{ $data->law }}</td>
                            <td>{{ $data->status }}</td>
                            <td>
                                @if($data->document_name)
                                    <a href="{{ asset('uploads/Profecionalbody/' . $data->document_name) }}" target="_blank" class="btn btn-primary btn-sm">
                                        View Document
                                    </a>
                                @else
                                    No Document
                                @endif
                            </td>
                            
                                <td>{{ $data->document_name }}</td>
                            
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>

        <!-- Medical Section -->
      

        <!-- Association Section -->
        <div class="mb-5">
            <h2>Professional Experience</h2>
           
            <table id="associationTable" class="table mb-0">
                <thead class="table-light">
                    <thead class="table-light">
    <tr>
        <th>ID</th>
                                        
                                        <th>I  have  a  license</th>
                                        <th>Issuing Body</th>
                                        <th>License Date</th>
        
      
    </tr>
</thead>
<tbody>
   @foreach($licence as $licence)
                                        <tr>
                                            <td>{{ $licence->id }}</td>
                                           
                                            <td>{{ $licence->has_license ?? 'N/A' }}</td>
                                            <td>{{ $licence->license_name ?? 'N/A' }}</td>
                                            <td>{{ $licence->license_date ?? 'N/A' }}</td>
            
            
        </tr>
   

                    @endforeach
                </tbody>
            </table>
        </div>
        <div class="card mt-4">
    <div class="card-body">
        <h2 class="fw-bold mb-3">Consultancy Assignments</h2>

        <div class="table-responsive">
            <table class="table table-bordered mb-0">
                <thead class="table-light">
                    <tr>
                        <th>#</th>
                        <th>Client</th>
                        <th>Sector</th>
                        <th>Completed</th>
                        <th>Completion Date</th>
                        <th>File</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($other as $index => $record)
                        <tr>
                            <td>{{ $index + 1 }}</td>
                            <td>{{ $record->Client }}</td>
                            <td>{{ $record->Sector }}</td>
                            <td>{{ $record->completed }}</td>
                            <td>{{ \Carbon\Carbon::parse($record->compedate)->format('d M Y') }}</td>
                            <td>
                                @if($record->document_name)
                                    <a href="{{ asset('uploads/Other/' . $record->document_name) }}" target="_blank">View</a>
                                @else
                                    <span class="text-muted">No Document</span>
                                @endif
                            </td>
                        </tr>
                    @empty
                        <tr><td colspan="6" class="text-center text-muted">No records found.</td></tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>
</div>

<!-- RESEARCH ASSIGNMENTS -->
<div class="card mt-4">
    <div class="card-body">
        <h2 class="fw-bold mb-3">Research Assignments</h2>

        <div class="table-responsive">
            <table class="table table-bordered mb-0">
                <thead class="table-light">
                    <tr>
                        <th>#</th>
                        <th>Client</th>
                        <th>Sector</th>
                        <th>Completed</th>
                        <th>Completion Date</th>
                        <th>Amount</th>
                        <th>File</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($others as $index => $record)
                        <tr>
                            <td>{{ $index + 1 }}</td>
                            <td>{{ $record->Client }}</td>
                            <td>{{ $record->Sector }}</td>
                            <td>{{ $record->completed }}</td>
                            <td>{{ \Carbon\Carbon::parse($record->compedate)->format('d M Y') }}</td>
                            <td>{{ $record->Amount ?? 'N/A' }}</td>
                            <td>
                                @if($record->document_name)
                                    <a href="{{ asset('uploads/Other/' . $record->document_name) }}" target="_blank">View</a>
                                @else
                                    <span class="text-muted">No Document</span>
                                @endif
                            </td>
                        </tr>
                    @empty
                        <tr><td colspan="7" class="text-center text-muted">No records found.</td></tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>
</div>

<!-- PUBLICATIONS -->
<div class="card mt-4">
    <div class="card-body">
        <h2 class="fw-bold mb-3">Publications</h2>

        <div class="table-responsive">
            <table class="table table-bordered mb-0">
                <thead class="table-light">
                    <tr>
                        <th>#</th>
                        <th>Journal / Publisher</th>
                        <th>Type / Title</th>
                        <th>Publication Date</th>
                        <th>File</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($publications as $index => $pub)
                        <tr>
                            <td>{{ $index + 1 }}</td>
                            <td>{{ $pub->Client }}</td>
                            <td>{{ $pub->completed }}</td>
                            <td>{{ \Carbon\Carbon::parse($pub->compedate)->format('d M Y') }}</td>
                            <td>
                                @if($pub->document_name)
                                    <a href="{{ asset('uploads/Other/' . $pub->document_name) }}" target="_blank">View</a>
                                @else
                                    <span class="text-muted">No Document</span>
                                @endif
                            </td>
                        </tr>
                    @empty
                        <tr><td colspan="5" class="text-center text-muted">No publications found.</td></tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>
</div>
        <div class="section-title">Referees</div>
        <table id="coreMandateTable" class="table mb-0">
            <thead class="table-light">
            <tr>
               <th>Employer</th>
        <th>Name</th>
        <th>Phone</th>
        <th>Email</th>
        <th>Position</th>
                                   

                        </tr>
                    </thead>
                    <tbody>
                       @foreach($referees as $referee)
    <tr>
        <td>{{ $referee->employer }}</td>
        <td>{{ $referee->refname }}</td>
        <td>{{ $referee->refphone }}</td>
        <td>{{ $referee->refemail }}</td>
        <td>{{ $referee->Position }}</td>
                        
            </tr>
            @endforeach
        </table>
    </div>
    </div>

    <!-- Bootstrap JS and Popper.js -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>

    <!-- Footer -->
    <style>
        .footer {
            background-color: rgb(127,98, 44);
            color: rgb(203, 211, 0); /* Text color */
            font-weight: bold; /* Bold text */
        }
    </style>
    
    <div class="footer">
        KSG APPLICATION - User Report | Generated on {{ date('d M Y, H:i A') }}
    </div>
    

</body>
</html>
