<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            position: relative;
        }

        /* Watermark */
        body::before {
            content: "{{ Auth::guard('HR')->user()->upn_no }}KSG";
            position: absolute;
            font-size: 60px;
            color: rgba(0, 0, 0, 0.1);
            top: 35%;
            left: 10%;
            transform: rotate(-30deg);
            z-index: -1;
            font-weight: bold;
        }

        .container {
            width: 100%;
            padding: 20px;
        }

        /* Logo Styling */
        .images-container {
            text-align: center;
            margin-bottom: 10px;
        }

        .logo-icon {
            margin: 0 10px;
            vertical-align: middle;
        }

        .header {
            text-align: center;
            background-color: #007bff;
            color: white;
            padding: 15px;
            font-size: 24px;
            font-weight: bold;
        }

        .sub-header {
            text-align: center;
            font-size: 18px;
            font-weight: bold;
            margin-top: 5px;
        }
        table thead th {
        background-color: rgb(203, 211, 0); /* Header background */
        color: rgb(127, 98, 44); /* Header text */
        padding: 10px;
        text-align: left;
    }

    table {
    border-collapse: collapse;
    width: 100%;
}

th {
    background-color: rgb(203, 211, 0); /* Background color */
    color: rgb(127, 98, 44); /* Text color */
    border: 1px solid black;
    padding: 10px;
    text-align: left;
}

td {
    border: 1px solid black;
    padding: 10px;
    text-align: left;
}

        th {
            background-color: #007bff;
            color: white;
        }

        .section-title {
            background-color: #f0f0f0;
            padding: 10px;
            font-size: 18px;
            font-weight: bold;
            margin-top: 20px;
        }

        /* Footer */
        .footer {
            position: fixed;
            bottom: 0;
            left: 0;
            width: 100%;
            text-align: center;
            font-size: 12px;
            padding: 10px;
            background-color: #007bff;
            color: white;
        }
    </style>
</head>
<body>

    <!-- Logo Section -->
    <div class="images-container">
        <img src="{{ public_path('assets/images/output-onlinepngtools (3).png') }}" class="logo-icon" alt="logo icon" height="66px" width="70px">
        <img src="{{ public_path('assets/images/COA_Line__1.png') }}" class="logo-icon" alt="logo icon" height="66px" width="5px">
        <img src="{{ public_path('assets/images/KSG Logo (1).png') }}" class="logo-icon" alt="logo icon" height="66px" width="90px">
    </div>

    <!-- Header -->
    <div class="header text-center" style="background-color: rgb(203, 211, 0); color: rgb(127, 98, 44); padding: 10px; font-size: 20px; font-weight: bold; border-radius: 5px;">
        Complete User Report
    </div>
    
    <style>
        .sub-header {
            color: rgb(203, 211, 0); /* Text color */
            font-weight: bold; /* Bold text */
        }
    </style>
    
    <div class="sub-header">Generated by {{ Auth::guard('HR')->user()->name }}</div>
    

    <div class="container">
        <!-- User Details -->
        <div class="section-title">User Details</div>
        <table id="coreMandateTable" class="table mb-0">
            <thead class="table-light">
            <tr>
                <th>Full Name</th>
                <td>{{ Auth::guard('HR')->user()->name }}</td>
                <th>Payroll  Number</th>
                <td>{{ Auth::guard('HR')->user()->upn_no }}</td>
                
                
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ Auth::guard('HR')->user()->email }}</td>
                <th>ID/Passport No</th>
                <td>{{ Auth::guard('HR')->user()->idnumber }}</td>
            </tr>
            <tr>
                <th>Phone Contact</th>
                <td>{{ Auth::guard('HR')->user()->phone }}</td>
                <th>Gender</th>
                <td>{{ Auth::guard('HR')->user()->gender }}</td>
            </tr>
            <tr>
                <th>Any Disability</th>
                <td>{{ Auth::guard('HR')->user()->disability }}:{{ Auth::guard('HR')->user()->disability_description }}</td>
                <th>Ethnicity</th>
                <td>{{ Auth::guard('HR')->user()->ethnicity }}</td>
            </tr>
            <tr>
                <th>  Home County</th>
                <td>{{ Auth::guard('HR')->user()->home_county }}</td>
                <th>Job  Group</th>
                <td>{{ Auth::guard('HR')->user()->job_group}}</td>
            </tr>
            <tr>
                <th>Campus</th>
                <td>{{ Auth::guard('HR')->user()->campus }}</td>
                <th>Date  of Birth</th>
                <td>{{ Auth::guard('HR')->user()->dob}}</td>
            </tr>

        </table>

        <!-- Academic Qualifications -->
        <div class="section-title">Academic Qualifications</div>
        <table id="example" class="table mb-0">
            <thead class="table-light">
            <tr>
                <th>#</th>
                            <th>Education Type</th>
                            <th>Institution</th>
                            <th>Course</th>
                            <th>Level</th>
                            <th>Start Date</th>
                            <th>End Date</th>
                            <th>Grade</th>
                          
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($academics as $index => $academic)
                        <tr>
                            <td>{{ $index + 1 }}</td>
                            <td>{{ $academic->Education_type }}</td>
                            <td>{{ $academic->institution }}</td>
                            <td>{{ $academic->course }}</td>
                            <td>{{ $academic->level }}</td>
                            <td>{{ date('d M Y', strtotime($academic->stdate)) }}</td>
                            <td>{{ date('d M Y', strtotime($academic->enddate)) }}</td>
                            <td>{{ $academic->grade }}</td>
            </tr>
            @endforeach
        </table>

        <!-- Work Experience -->
        <div class="section-title">Work Experience</div>
        <table id="coreMandateTable" class="table mb-0">
            <thead class="table-light">
            <tr>
                <th>Employer</th>
                            <th>Job Title</th>
                            <th>Country</th>
                            <th>Start Date</th>
                            <th>End Date</th>
                            <th>Location</th>
                            <th>Job Description</th>
                            <th>Duties  and  Responsibilities</th>
                            
                      

                        </tr>
                    </thead>
                    <tbody>
                        @forelse($experiences as $experience)
                        <tr>
                            <td>{{ $experience->employer }}</td>
                            <td>{{ $experience->job_title }}</td>
                            <td>{{ $experience->country }}</td>
                            <td>{{ date('d M Y', strtotime($experience->stdate)) }}</td>
                            <td>{{ date('d M Y', strtotime($experience->enddate)) }}</td>
                            <td>{{ $experience->location }}</td>
                            <td>{{ $experience->expartise }}</td>
                            <td>{{ $experience->duties }}</td>
                        
            </tr>
            @endforeach
        </table>
    </div>
    <div class="container mt-5">
        <!-- Core Mandate Section -->
        <div class="mb-5">
            <h2>Core Mandate</h2>
            
            <table id="coreMandateTable" class="table mb-0">
                <thead class="table-light">
                    <tr>
                        <th>ID</th>
                        
                        <th>Core Mandate</th>
                        <th>Selected Count</th>
                        <th>Date</th>
                        <th>Status</th>
                        
                    </tr>
                </thead>
                <tbody>
                    @foreach($coremandate as $item)
                        <tr>
                            <td>{{ $item->id }}</td>
                           
                            <td>{{ $item->comandate ?? 'N/A' }}</td>
                            <td>{{ $item->selected_count ?? 'N/A' }}</td>
                            <td>{{ $item->date }}</td>
                            <td>{{ $item->status }}</td>
                            
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>

        <!-- Licenses Section -->
        <div class="mb-5">
            <h2>Practising Licences</h2>
           
            <table id="licensesTable" class="table mb-0">
                <thead class="table-light">
                    <tr>
                        <th>ID</th>
                        
                        <th>I have a licence</th>
                        <th>License Name</th>
                        <th>License Date</th>
                        <th>Document</th>
                        <th>Licance  Name</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($licence as $licence)
                        <tr>
                            <td>{{ $licence->id }}</td>
                            
                            <td>{{ $licence->has_license ?? 'N/A' }}</td>
                            <td>{{ $licence->license_name ?? 'N/A' }}</td>
                            <td>{{ $licence->license_date ?? 'N/A' }}</td>
                            <td>
                                @if($licence->document_name)
                                    <a href="{{ asset('uploads/Licence/' . $licence->document_name) }}" target="_blank" class="btn btn-primary btn-sm">
                                        View Document
                                    </a>
                                @else
                                    No Document
                                @endif
                            </td>
                            <td>
                                {{ $licence->document_name }}
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>

        <!-- Professional Body Section -->
        <div class="mb-5">
            <h2>Professional Body</h2>
            
            <table id="professionalBodyTable" class="table mb-0">
                <thead class="table-light">
                    <tr>
                        <th>ID</th>
                        <th>I am a member</th>
                        <th>Professional Body Name</th>
                        <th>Regulating Law/Statute</th>
                        <th>Status</th>
                        <th>Certificate</th>
                        <th>Certificate  Name</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($profecionalbodies as $data)
                        <tr>
                            <td>{{ $data->id }}</td>
                            <td>{{ $data->is_member }}</td>
                            <td>{{ $data->professional_body }}</td>
                            <td>{{ $data->law }}</td>
                            <td>{{ $data->status }}</td>
                            <td>
                                @if($data->document_name)
                                    <a href="{{ asset('uploads/Profecionalbody/' . $data->document_name) }}" target="_blank" class="btn btn-primary btn-sm">
                                        View Document
                                    </a>
                                @else
                                    No Document
                                @endif
                            </td>
                            
                                <td>{{ $data->document_name }}</td>
                            
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>

        <!-- Medical Section -->
        <div class="mb-5">
            <h2>Food handler  Certificates</h2>
           
            <table id="medicalTable" class="table mb-0">
                <thead class="table-light">
                    <tr>
                        <th>ID</th>
                       
                        <th>Examination Name</th>
                        <th>I have</th>
                        
                        <th>Date</th>
                        <th>Status</th>
                        <th>Document</th>
                        <th>Document Name</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($medical as $data)
                        <tr>
                            <td>{{ $data->id }}</td>
                           
                            <td>{{ $data->name_exam }}</td>
                            <td>{{ $data->condition ?? 'N/A' }}</td>
                            <td>{{ $data->date ?? 'N/A' }}</td>
                            <td>{{ $data->status }}</td>
                            <td>
                                @if($data->document_name)
                                    <a href="{{ asset('uploads/Medical/' . $data->document_name) }}" target="_blank" class="btn btn-primary btn-sm">
                                        View Document
                                    </a>
                                @else
                                    No Document
                                @endif
                            </td>
                            
                                <td>{{ $data->document_name }}</td>
                            
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>

        <!-- Association Section -->
        <div class="mb-5">
            <h2>Association</h2>
           
            <table id="associationTable" class="table mb-0">
                <thead class="table-light">
                    <tr>
                        <th>ID</th>
                        
                        <th>Am I a member</th>
                        <th>Association Name</th>
                        <th>Membership Status</th>
                        <th>Document</th>
                        <th>Document Name</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($associations as $data)
                        <tr>
                            <td>{{ $data->id }}</td>
                           
                            <td>{{ $data->condition }}</td>
                            <td>{{ $data->association_name }}</td>
                            <td>{{ $data->status }}</td>
                            <td>
                                @if($data->document_name)
                                    <a href="{{ asset('uploads/Association/' . $data->document_name) }}" target="_blank" class="btn btn-primary btn-sm">
                                        View Document
                                    </a>
                                @else
                                    No Document
                                @endif
                            </td>
                            
                                <td>{{ $data->document_name}}</td>
                        
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>

    <!-- Bootstrap JS and Popper.js -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>

    <!-- Footer -->
    <style>
        .footer {
            background-color: rgb(127,98, 44);
            color: rgb(203, 211, 0); /* Text color */
            font-weight: bold; /* Bold text */
        }
    </style>
    
    <div class="footer">
        KSG APPLICATION - User Report | Generated on {{ date('d M Y, H:i A') }}
    </div>
    

</body>
</html>
